"""initial empty migration

Revision ID: 084c524a5e1b
Revises: 
Create Date: 2026-03-17 17:15:07.182487

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '084c524a5e1b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
