"""add sandbox_executions table

Revision ID: d802209ec9d8
Revises: 83d7f740ef1c
Create Date: 2026-03-18 16:22:18.591442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd802209ec9d8'
down_revision: Union[str, Sequence[str], None] = '83d7f740ef1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandbox_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cpu_seconds', sa.Float(), nullable=True),
    sa.Column('memory_peak_mb', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_executions_agent_run_id'), 'sandbox_executions', ['agent_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandbox_executions_agent_run_id'), table_name='sandbox_executions')
    op.drop_table('sandbox_executions')
    # ### end Alembic commands ###
